# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-23 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rickroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkpicture',
            name='bytes',
            field=models.BinaryField(),
        ),
    ]
