# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rickroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='link',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rickroll.LinkPicture/bytes/filename/mimetype'),
        ),
    ]
